config/routes.rb
Flitter::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'registrations' }
  

  root "welcome#index"

    
  resources :microposts,  only: [:create, :destroy] do
    resources :comments,  only: [:new, :create, :destroy]
  end
    
  resources :users, only: [:index, :show, :destroy] do
    member do
      get     :following, :followers
      post    :follow
      delete  :unfollow
    end
  end
    
  get     '/home'                   => 'home#index', as: :user_root
  patch   'notifications/read_all'  => 'notifications#read_all'
  
    

  

end

app/models/user.rb
class User < ActiveRecord::Base
  devise :registerable, :confirmable,  :database_authenticatable,
         :recoverable,  :rememberable, :validatable
  
  has_many :comments,       dependent:    :destroy
  has_many :microposts,     dependent:    :destroy
  has_many :notifications,  dependent:    :destroy
  
  has_many :notification_senders,   class_name:  "Notification",
                                    foreign_key: "sender_id",
                                    dependent:   :destroy
  has_many :active_relationships,   class_name:  "Relationship",
                                    foreign_key: "follower_id",
                                    dependent:   :destroy
  has_many :passive_relationships,  class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
                                    
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  
  before_save { self.email = email.downcase }
  
  validates :name,  presence: true, length: { maximum: 50 }
      
  #  --------------- ------- Methods ------- -------------------                  
  def feed
    res = microposts.union(
      Micropost.joins("JOIN relationships ON ((microposts.user_id = relationships.followed_id AND relationships.follower_id = #{id} ))")
    ).order(created_at: :desc)
  end
    
  def follow(other_user)
    if active_relationships.create(followed_id: other_user.id).valid?
      other_user.send_notification(self, :followed)
    else
      raise Errors::FlitterError.new(I18n.t(:follow_error))
    end
  end
  
  def unfollow(other_user)
    relation = active_relationships.find_by(followed_id: other_user.id)
    if relation.present? && relation.destroy
      other_user.send_notification(self, :unfollowed)
    else
      raise Errors::FlitterError.new(I18n.t(:unfollow_error))
    end
  end
  
  def self.current_user=(user)
    Thread.current[:user] = user
  end
  
  def self.current_user
    Thread.current[:user]
  end
  
  def following?
    following.where(id: User.current_user.id).any?
  end
  
  def followed?
    User.current_user.following.where(id: id).any?
  end
  
  def send_notification(sender_user, notification_type)
    notifications.create(sender_id: sender_user.id, notification_type: notification_type)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  #  GET /users
  def index
    @users = User.where(role: :member).paginate(page: params[:page], per_page: 3)
  end
    
  #  GET /users/:id
  def show
    @microposts = @user.microposts.descending.paginate(page: params[:page], per_page: 3)
  end
  
  #  DELETE /users/:id
  def destroy
    if @user.destroy
      flash[:success] = t(:user_deleted)
    else
      flash.now[:danger]  = t(:user_delete_error)
    end
    redirect_to :back || users_path # two paths i.e. from user list or from following/follower list
  end
  
  #  GET /users/:id/following
  def following
    @title = t(:following_title)
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  #  GET /users/:id/followers
  def followers
    @title = t(:follower_title)
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end
  
  #  POST /users/:id/follow
  def follow
    current_user.follow(@user)
    respond_to do |format|
      format.js
    end
  end

  #  DELETE /users/:id/unfollow
  def unfollow
   current_user.unfollow(@user)       
    respond_to do |format|
      format.js
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/views/users/_follow.html.erb
<%= form_for(current_user, url: follow_user_path, html: { method: :post }, remote: true) do |f| %>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user == @user %>
  <div id="follow_form">
  <% if can? :follow, @user %>
    <%= render 'follow' %>
  <% else %>
    <%= render 'unfollow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>

  <%= f.label :email %>
  <%= f.email_field :email, class: 'form-control' %>

  <%= f.label :password %>
  <%= f.password_field :password, class: 'form-control' %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation, class: 'form-control' %>

  <%= f.submit button_text: button_text, class: "btn btn-primary" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user, url: unfollow_user_path, html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  
  <% if can? :destroy, user %> <!-- current_user.admin? && current_user != user -->
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", :button_text => "Update User" %>

    <!-- <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div> -->
  </div>
</div>

app/views/users/follow.js.erb
$("#follow_form").html("<%= escape_javascript(render('unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');
<% @user.microposts.each do |micropost| %>
  $("#add-comment-on-post-<%= micropost.id %>").html("<%= escape_javascript(render 'shared/comment_form', micropost: micropost) %>");
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form", :button_text => "Create User"%>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if user_signed_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><b>Microposts:</b> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate %>
    <% end %>
  </div>
</div>

app/views/users/unfollow.js.erb
$("#follow_form").html("<%= escape_javascript(render('follow')) %>");
$("#followers").html('<%= @user.followers.count %>');
<% @user.microposts.each do |post| %>
  $("#add-comment-on-post-<%= post.id %>").empty();
<% end %>