config/routes.rb
Flitter::Application.routes.draw do
  
  devise_for :users, controllers: { registrations: 'registrations' }
  

  root "welcome#index"

    
  resources :microposts,  only: [:create, :destroy] do
    resources :comments,  only: [:new, :create, :destroy]
  end
    
  resources :users, only: [:index, :show, :destroy] do
    member do
      get     :following, :followers
      post    :follow
      delete  :unfollow
    end
  end
    
  get     '/home'                   => 'home#index', as: :user_root
  patch   'notifications/read_all'  => 'notifications#read_all'
  
    

  

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Flitter sample application</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Flitter", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
        	<li><%= link_to "Home", user_root_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_registration_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", destroy_user_session_path, method: "delete" %>
              </li>
            </ul>
          </li>
          
          <%= render 'shared/user_notifications' %>
          
        <% else %>
        	<li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log in", new_user_session_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title><%= page_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <div id="flash_messages">
        <%= render 'shared/flash_messages'%>
      </div>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <!-- <%= debug(params) if Rails.env.development? %> -->
  </body>
</html>